name: Build documentation
on: [push]
jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Install doxygen
        run: sudo apt-get install -y doxygen
      - name: Build
      - run: doxygen
