name: Build documentation
on: [push]
jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install doxygen
        run: sudo apt-get install -y doxygen
      - name: Build
        run: doxygen
